# Set up the prompt

autoload -U colors && colors # Enable colors in prompt

source /home/build/zsh-git-prompt-master/zshrc.sh
# an example prompt
PROMPT='%{$fg[blue]%}docker#%{$reset_color%}%{$fg[green]%}%B%~%{$reset_color%}%b$(git_super_status) %# '

setopt histignorealldups

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias ll="ls -l -h"
alias df="df -h"
alias du="du -h"
alias mj="make -j11"

export GIT_EDITOR=/usr/bin/vim
export DEBEMAIL="Flavien Bridault <fbridault@ircad.fr>"
export DEB_BUILD_OPTIONS="parallel=11"

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable hg git bzr svn

